# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: CopyFiles@2
  displayName: 'Copy Files to ArtifactStagingDirectory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/k8s/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true
- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: 'dockerconn1'
    repository: 'pirai/testimage'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: KubernetesManifest@0
  inputs:
    action: 'createSecret'
    kubernetesServiceConnection: 'k8sconn1'
    secretType: 'dockerRegistry'
    secretName: 'k8ssecret'
    dockerRegistryEndpoint: 'dockerconn1'
- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'k8sconn1'
    manifests: 'k8s/template.yaml'
    imagePullSecrets: '$(k8ssecret)'
    rolloutStatusTimeout: '60'
